### PR TITLE
fixtures: Move exercises into exercises directory; reapply #12

### PR DESCRIPTION
**Pull request by petertseng**
PR #17 conflicted with PR #12 (not a git merge conflict, but a conflict in the sense that the tests pass for each individually but fail when both are merged), causing PR #12 to be reverted. This PR fixes the conflict (fixtures in an inconsistent state, with exercises outside an `exercises` directory).

Details in individual commit messages.

Possible questions to consider before merge:

---

1. OK to leave the commit name as `Revert "Revert "implementation: Test for symlinked files""`? Don't know whether people don't like to see revert-of-revert. I can suggest alternative `Reapply "implementation: Test for symlinked files"`
2. Should we test for exercises outside the `exercises` directory? But testing it *in this repository* will only affect fixture integrity. It is possible this is important to test in this repository. If so, where might be the right place to put the test?
2. Another thing to make sure is that `configlet` expects the same: It must not accept exercises outside the `exercises` directory (if the `exercises` directory exists), since the presence of any such exercise would cause `trackler` to serve only the README and no other files.

### CODE REVIEW

**Comment by Insti** [comment]
>  OK to leave the commit name as Revert "Revert "implementation: Test for symlinked files""? Don't know whether people don't like to see revert-of-revert. I can suggest alternative Reapply "implementation: Test for symlinked files"

I like "Reapply" better than "revert revert".

>  Should we test for exercises outside the exercises directory? But testing it in this repository will only affect fixture integrity. It is possible this is important to test in this repository. If so, where might be the right place to put the test?

I don't think this is necessary to explicitly test for, now we have the correct fixture files any additions should be in the correct places and someone would have to go out of their way to create an invalid structure and if it happens it will cause other failures as we have seen.

>  Another thing to make sure is that configlet expects the same: It must not accept exercises outside the exercises directory (if the exercises directory exists), since the presence of any such exercise would cause trackler to serve only the README and no other files.

Configlet is the right place for tests that the track structure is correct. Creating an issue there is probably a good idea.

**Comment by petertseng** [comment]
I changed to "Reapply" - commit contents haven't changed.

**Comment by kytrinyx** [comment]
I like 'reapply' too.

> Should we test for exercises outside the exercises directory?

If we still have tracks that have not moved their exercises, then we should probably keep some sort of test that makes sure that we can find exercises at the deprecated location. I'll see what I can find.

> Another thing to make sure is that configlet expects the same

Configlet assumes that the exercises are either in the exercises directory, or not. No mixtures.

**Comment by kytrinyx** [comment]
We still have tracks that haven't moved their exercises:

* coldfusion
* cpp
* haxe
* nasm
* tcl
* vbnet

The only live track is C++. There's an open PR, but the build is failing: https://github.com/exercism/xcpp/pull/108

**Comment by kytrinyx** [comment]
Since this doesn't change production code, only tests and fixtures, I'm going to go ahead and merge it. Perhaps instead of adding a test for having exercises in the root directory, we can get the PR in C++ merged (as well as adding some PRs for the inactive tracks).

**Comment by Insti** [comment]
Making an issue in the main exercism.io repository to update those remaining orphan tracks could be a good idea.

**Comment by kytrinyx** [comment]
Yeah, good call. An issue in exercism/exercism.io, and update each of the existing issues to link back to it so that we get a live todo list there.

**Pull request merged**
