### PR TITLE
Extract Metadata concept from Problem

### PR DESCRIPTION
**Pull request by IanWhitney**
This is a prepatory refactoring for #22

No functional changes introduced in this change.

I'm extracting the concepts of creating and reading the metadata file out of Problem and into a new Metadata class. This means I now know the API that any metadata-like class will have to support.

The behavior of Metadata is tested in both its own test file as well as the existing Problem test file.

### CODE REVIEW

**Comment by Insti** [comment]
I like where this is going.

I'd remove the `for_problem` factory method and just use an initializer that took the file data:
```
 @metadata = Metadata.new( YAML.load(File.read(filename)) )
```
This:
* Simplifies the `Metadata` class
* Keeps the file location responsibility/knowledge together.
* Removes `Metadata`s dependency on `Problem`
* Allows `Metadata` to act as an immutable "data object"

**Comment by Insti** [comment]
It's probably best to continue development on this branch with atomic commits rather than waiting for each PR to be merged.

I think @kytrinyx is the only one with write access to this repository, and it can be some time before she finds time to review/merge changes here.

**Comment by IanWhitney** [comment]
I mostly stole the `for` syntax from @kytrinyx and Sandi Metz, so let's see what she says. I can go either way, though I do like [declarative builders](http://programming.ianwhitney.com/blog/2014/04/13/4-simple-rules-and-declarative-builders/)!

Good to know about the write access. My plan with this PR was to get general buy in on my approach. Once I have that I can do all of the work in the branch and make a big PR later.

**Comment by Insti** [comment]
Thanks for the blog link. I like declarative builders too, and think that they can be very useful at conveying meaning.

The reason I don't think `for_problem` is appropriate in this case is that there is only one thing that the metadata is going to be for (a problem), and  `Metadata`[1] now needs to know:
* What the `Problem.root` is.
* What `Problem.slug` is.
* What the metadata filename is.
* How to construct the path to the metadata file.
* How to check if a file exists.
* How to read a file.

These are already things that `Problem`[2] knows and is using to access other files it needs.

Without it, all `Metadata` needs to know is.
* How to parse a YAML string.
* How to do the string conversion on the relevant properties.

An alternative declarative builder might be[3]: 
```
@metadata = Metadata.from_yaml_string( File.read(filename) )
```
Which is still clear about what it is constructing but doesn't require `Metadata` to know anything about the rest of the application.



Footnotes:
1. If it was called `ProblemMetadata` would that change anything?
1. Whether `Problem` is appropriately named and has the right number of responsibilities  is another discussion that is not in scope here.
1. This would go on line [112 of the original version](https://github.com/exercism/trackler/pull/23/files#diff-1ca51266c8df3f4207fd7ef78e79288aL112), with the rest of that method remaining unchanged.

**Comment by IanWhitney** [comment]
My eventual implementation will probably look like

```ruby
class Metadata
  def self.for_problem(problem:)
    if file_exists?
      # return Metadata instance
    else
      # return NullMetadata instance
    end
  end
end
```

So I don't think the `Metadata.from_yaml_string( File.read(filename) )` approach would work, because it relies on the file existing.

**Comment by kytrinyx** [comment]
Will we eventually have two `Metadata` types? E.g. `SharedMetadata` and `LocalMetadata`? If so, I would probably use `for` so that we get the right type.

If we're just going to have one type of metadata, and only one way to create them, I think I'd use `new`... unless it becomes a pain in the ass to test because we suddenly need expensive setup. Then I might use a `for` that does the expensive stuff and `new` that takes a stupidified version of the data.

I like where this is going, though. I think it's definitely the right move to pull out the metadata into its own thing.

**Comment by IanWhitney** [comment]
Ah, right @kytrinyx I may be going about this wrong. It's not that a problem has/lacks a Metadata file, it's that it either has a Common Metadata or Track Metadata file, right?

In other words, if a track implements their own custom exercise, they'll also have to provide their own metadata and description files.

**Comment by kytrinyx** [comment]
@IanWhitney Yeah, I think so. Of course... I always tend to think I know things, until I get dirty in the code. Then everything tends to look different. In other words: it seems reasonable, but if once you start playing with it it seems silly, then I am happy to change my mind.

**Comment by IanWhitney** [comment]
Yeah, things certainly get harder when you start actually looking at the code!

I'm going to talk through this to see what I understand.

The top-level `Trackler` class has `Problems` and `Tracks`.

`Trackler.Problems` is a collection of `Problem` objects, which are built up from the files stored in the `common` directory. The expectation of the `common` directory being where these things are stored is set [here](https://github.com/exercism/trackler/blob/803cc72f78596f814a220c45f5cdd248c4090b62/lib/trackler/problems.rb#L37) in Problems. Trackler passes it a `root` path and then Problems looks under that root for a `common` directory where all problem descriptions are stored.

`Trackler.Tracks` returns a collection of `Track` objects. Each of those objects has an `implementations` collection. Each `implementation` object has a `Problem`, which is another Problem object.

But the `Problem` objects within `Implementation` are created the same way as our earlier `Problem` objects. They are given the root path and [only look in the 'common' directory](https://github.com/exercism/trackler/blob/803cc72f78596f814a220c45f5cdd248c4090b62/lib/trackler/problem.rb#L116).

Since no `Problem` object can ever look anywhere but in `common` it can never find a metadata file that exists inside a track's directory.

So, based on that, I think that gives me a way forward. Refactor Problem so that it can be created as both either a Common or Track-Specific one.

**Comment by IanWhitney** [comment]
This conversation has been good (and should probably continue). But this PR is no longer the way the code is going, so I'm going to close it.

**Comment by kytrinyx** [comment]
@IanWhitney your summary of the situation sounds exactly right. I think you've got the right way forward.

**Pull request closed without merging**
